# Generated by Django 5.1.6 on 2025-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_product_meta_description_product_meta_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
