# Generated by Django 5.1.6 on 2025-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
